[tool.black]
line-length = 79

[tool.isort]
multi_line_output = 3
include_trailing_comma = true

[tool.pylint.'MESSAGES CONTROL']
extension-pkg-whitelist = "pydantic"

[tool.pylint.'BASIC']
good-names = "e, db, Session, t, i, c, df, x, y, v, f"

[tool.pylint.'LOGGING']
disable = "logging-fstring-interpolation"

[tool.pytest.ini_options]
pythonpath = [
  "confluencedocs"
]
