name: Python application to send monthly reminder email

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 1 * *' # Run at 07:00 (UTC) on day-of-month 1.

jobs:
  build_run:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install package dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_cronjob.txt

      - name: Run the script with the required environment variables
        env:
          PORT: ${{ secrets.PORT }}
          SERVER: ${{ secrets.SERVER }}
          SENDER: ${{ secrets.SENDER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          EMAILS: ${{ secrets.EMAILS }}
        run: python send_monthly_reminder.py
